tap "marianposaceanu/tap"
tap "borkdude/brew"

brew "babashka"
brew "fzf"
brew "zoxide"
brew "zsh-autosuggestions"
brew "mextdisplay"
brew "rz"
brew "ripgrep"
brew "bat"
brew "ruby"
brew "openjdk"
brew "universal-ctags"
brew "tmux"
brew "vim"
