set nocompatible

" Pathogen
call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on

syntax on

" Theme
set background=dark
colorscheme base16-railscasts     " preview http://chriskempson.github.io/base16
                                  " base16-eighties
                                  " base16-railscasts
                                  " base16-tomorrow

" general stuff
set number
set hlsearch
set showmatch
set incsearch
set autoindent
set history=1000
set cursorline
set expandtab
set autochdir
set backspace=indent,eol,start    " Intuitive backspacing.
set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a
                                  "  capital letter.
set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.
set wrap                          " Turn on line wrapping.
set linebreak                     " ^
set scrolloff=3                   " Show 3 lines of context around the cursor.
set laststatus=2                  " Show the status line all the time
set encoding=utf-8                " Use UTF-8 everywhere.
set ttimeoutlen=50                " fix for slow after INSERT exit mode

if has('win32')                   " save swp files into tmp
  set dir=c:\\tmp
else
  set dir=~/tmp
endif
set nobackup                      " Don't make a backup.
set nowritebackup                 " And again.

set expandtab                     " Use spaces instead of tabs
set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set softtabstop=2                 " This makes the backspace key treat the two
                                  "  spaces like a tab (so one backspace goes
                                  "  back a full 2 spaces).

" Airline settings
" let g:airline_powerline_fonts=1
let g:airline_theme="simple"
let g:airline_left_sep = '»'
let g:airline_right_sep = '«'
let g:airline_linecolumn_prefix = '¶ '
let g:airline_paste_symbol = 'ρ'
let g:airline_paste_symbol = 'Þ'


" Nerdtree
" autocmd vimenter * NERDTree
let NERDTreeShowBookmarks=1
let NERDTreeChDirMode=0
let NERDTreeQuitOnOpen=1
let NERDTreeMouseMode=2
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\.pyc','\~$','\.swo$','\.swp$','\.git','\.hg','\.bzr']
let NERDTreeKeepTreeInNewTab=1
let g:nerdtree_tabs_open_on_gui_startup=0
map <silent> <F1> :NERDTreeToggle %:p:h<CR>

" I have no idea what this does
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

" Toogle search highlighting
autocmd BufNewFile,BufRead Gemfile set filetype=ruby
nnoremap <F3> :set hlsearch!<CR>

" Toogle alternate shortcut for BuffExplorer
"  explore/next/previous: Alt-F12, F12, Shift-F12.
nnoremap <silent> <M-F12> :BufExplorer<CR>
nnoremap <silent> <F12> :bn<CR>
nnoremap <silent> <S-F12> :bp<CR>

" Bye bye arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" spell checking and automatic wrapping at the recommended 72 columns
" for gitcommits
autocmd Filetype gitcommit setlocal spell textwidth=72

" treat *.ru files with ruby syntax highlighting
au BufRead,BufNewFile *.ru setfiletype ruby

" show whitespace
let g:ShowTrailingWhitespace = 1

" auto delete trailling whitespace
let g:DeleteTrailingWhitespace = 1

" Sorting words (not lines) in VIM
" via http://stackoverflow.com/questions/1327978/sorting-words-not-lines-in-vim
vnoremap <F2> d:execute 'normal i' . join(sort(split(getreg('"'))), ' ')<CR>

" check code complexity and duplication for current file
if has("gui_win32")
  map <leader>x :!cls &&
        \ echo '----- Complexity -----' && flog % &&
        \ echo '----- Duplication -----' && flay %<cr>
else
  map <leader>x :!clear &&
        \ echo '----- Complexity -----' && flog % &&
        \ echo '----- Duplication -----' && flay %<cr>
end

" open gist after it's been created
let g:gist_open_browser_after_post = 1

" map Ack
map <leader>a :Ack!<space>
" search for word under cursor with Ack
map <leader>A :Ack! "<C-r>=expand('<cword>')<CR>"
