set nocompatible

" Pathogen
call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on

" general stuff
syntax on
set number
set hlsearch
set showmatch
set incsearch
set autoindent
set history=1000
set cursorline
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set autochdir
set backspace=indent,eol,start    " Intuitive backspacing.
set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.
set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.
set wrap                          " Turn on line wrapping.
set linebreak                     " ^
set scrolloff=3                   " Show 3 lines of context around the cursor.
set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location
"set shiftwidth=2                 " And again, related.
set tabstop=2                     " Global tab width.
set expandtab                     " Use spaces instead of tabs
set laststatus=2                  " Show the status line all the time
set encoding=utf-8                " Use UTF-8 everywhere.

" Powerline awesome patched typeface
" let g:Powerline_symbols="fancy"

" airline settings
let g:airline_powerline_fonts=1
" remove separators
let g:airline_left_sep=''
let g:airline_right_sep=''
" remove unused modes
let g:airline_enable_fugitive=0
let g:airline_enable_syntastic=0
" set second section to filename
let g:airline_section_b="%f"
" empty third and fourth sections
let g:airline_section_c=""
let g:airline_section_x=""
" put filetype in fifth section
let g:airline_section_y="%Y"
" fix for slow after INSERT exit mode
set ttimeoutlen=50

" Nerdtree
" autocmd vimenter * NERDTree
let NERDTreeShowBookmarks=1
let NERDTreeChDirMode=0
let NERDTreeQuitOnOpen=1
let NERDTreeMouseMode=2
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\.pyc','\~$','\.swo$','\.swp$','\.git','\.hg','\.svn','\.bzr']
let NERDTreeKeepTreeInNewTab=1
let g:nerdtree_tabs_open_on_gui_startup=0

" Nerdtree toogle key
map <silent> <F1> :NERDTreeToggle %:p:h<CR>

" Theme
set background=dark
colorscheme base16-default

set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

" Toogle search highlighting
autocmd BufNewFile,BufRead Gemfile set filetype=ruby
nnoremap <F3> :set hlsearch!<CR>

" Bye bye arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" Tab mappings.
map <leader>tt :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
map <leader>tn :tabnext<cr>
map <leader>tp :tabprevious<cr>
map <leader>tf :tabfirst<cr>
map <leader>tl :tablast<cr>
map <leader>tm :tabmove


" spell checking and automatic wrapping at the recommended 72 columns
autocmd Filetype gitcommit setlocal spell textwidth=72

" treat *.ru files with ruby syntax highlighting
au BufRead,BufNewFile *.ru setfiletype ruby

" show whitespace
let g:ShowTrailingWhitespace = 1

" auto delete trailling whitespace
let g:DeleteTrailingWhitespace = 1

" Map e and v to open files in the same directory as the current file
cnoremap %% <C-R>=expand('%:h').'/'<cr>
" map <leader>e :edit %%
" map <leader>v :view %%

